steps:
              - task: DownloadPipelineArtifact@2
                displayName: Download Build Artifacts - ADF ARM templates
                inputs:
                  artifactName: '$(CommonPublishArmTemplateName)'
                  targetPath: '$(WorkspaceArmTemplateDirectory)'
              - script: dir
                displayName: List files in Workspace
                workingDirectory: '$(WorkspaceArmTemplateDirectory)'

              - task: AzureResourceManagerTemplateDeployment@3
                displayName: 'Deploying to Dev RG task'
                inputs:
                  deploymentScope: 'Resource Group'
                  #azureResourceManagerConnection: '$(DevDeployDevOpsConnection)'
                  #subscriptionId: '$(DevSubscriptionId)'
                  #action: 'Create Or Update Resource Group'
                  #resourceGroupName: '$(DevAdfRgName)'
                  #location: '$(DevAdfLocation)'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(WorkspaceArmTemplateDirectory)/ARMTemplateForFactory.json'
                  csmParametersFile: '$(WorkspaceArmTemplateDirectory)/ARMTemplateParametersForFactory.json'
                  overrideParameters: '-factoryName "$(DevAdfName)" -LS_SalesDatabase_connectionString "$(DevSalesDbConnectionString)" -LS_DataLake_properties_typeProperties_url "$(DevDataLakeUrl)" -LS_KeyVault_properties_typeProperties_baseUrl "$(DevKeyVaultBaseUrl)"'
                  deploymentMode: 'Incremental'